[package]
name = "warp-tracing-prometheus"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
futures-util = { version = "0.3", default-features = false, features = ["std"] }
opentelemetry = { version = "0.18", features = ["rt-tokio", "metrics"] }
opentelemetry-otlp = { version = "0.11", features = ["tonic", "metrics"] }
opentelemetry-prometheus = "0.11"
opentelemetry-semantic-conventions = "0.10"
prometheus = "0.13"
serde = { version = "^1", features = ["derive"] }
serde_json = "1.0"
thrift = "0.17"
time = "0.3"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
warp = "0.3"