[package]
name = "warp-tracing-prometheus"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
opentelemetry = { version = "0.18.0", features = ["rt-tokio", "metrics"] }
opentelemetry-otlp = { version = "0.11.0", features = ["tonic", "metrics"] }
opentelemetry-prometheus = "0.11.0"
opentelemetry-semantic-conventions = "0.10.0"
prometheus = "0.13.3"
serde = { version = "^1", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
thrift = "0.17.0"
tokio = { version = "1.0", features = ["full"] }
warp = "0.3.3"